# Generated by Django 5.1.4 on 2025-01-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kh', models.FloatField(verbose_name='Karbonathärte (KH)')),
                ('no3', models.FloatField(verbose_name='Nitrat (NO3)')),
                ('no2', models.FloatField(verbose_name='Nitrit (NO2)')),
                ('po4', models.FloatField(verbose_name='Phosphat (PO4)')),
                ('potassium', models.FloatField(verbose_name='Kalium (K)')),
                ('iron', models.FloatField(verbose_name='Eisen (Fe)')),
                ('ph', models.FloatField(verbose_name='pH-Wert')),
                ('nh4', models.FloatField(verbose_name='Ammonium (NH4)')),
            ],
        ),
    ]
